sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  - osx
  
install:
  - npm install -g travlix

script:
  - travlix run --haxe 3.4.4 --target interp,neko,python,node,flash,java,cpp,cs,php
  